export type ComponentId = (typeof catalog)[number]["id"];
export const catalog = [
  {
    id: "button",
    name: "Button",
    zh: "按钮",
    group: "Actions",
    description: "Press anywhere. Pull the glass. Release to settle.",
    summary: "按住任意位置，拉伸玻璃，松手回弹。",
    api: "GlassButton",
    props: [
      ["variant", '"default" | "solid" | "ghost"', '"default"'],
      ["size", '"small" | "default" | "large"', '"default"'],
      ["disabled", "boolean", "false"],
      ["onClick", "MouseEventHandler", "—"],
    ],
    code: "<GlassButton onClick={() => setCount(count + 1)}>Continue</GlassButton>",
  },
  {
    id: "button-group",
    name: "Button Group",
    zh: "按钮组",
    group: "Actions",
    description: "Independent actions in one continuous glass surface.",
    summary: "一块连续玻璃，组合多个独立操作。",
    api: "GlassButtonGroup",
    props: [
      ["label", "string", "required"],
      ["orientation", '"horizontal" | "vertical"', '"horizontal"'],
      ["children", "ReactNode", "buttons or links"],
      ["…props", "HTMLAttributes<HTMLDivElement>", "—"],
    ],
    code: '<GlassButtonGroup label="Zoom">\n        <GlassButton onClick={() => setZoom(value => Math.max(25, value - 25))} disabled={zoom <= 25}>−</GlassButton>\n        <GlassButton onClick={() => setZoom(100)} aria-label="Reset zoom">{zoom}%</GlassButton>\n        <GlassButton onClick={() => setZoom(value => Math.min(200, value + 25))} disabled={zoom >= 200}>+</GlassButton>\n      </GlassButtonGroup>',
  },
  {
    id: "switch",
    name: "Switch",
    zh: "开关",
    group: "Inputs",
    description: "Opaque at rest. Pure glass in your hands.",
    summary: "静止时纯白，按下后连续展开为玻璃。",
    api: "GlassSwitch",
    props: [
      ["checked", "boolean", "uncontrolled"],
      ["onCheckedChange", "(checked: boolean) => void", "—"],
      ["size", '"default" | "small"', '"default"'],
      ["ariaLabel", "string", "required label"],
    ],
    code: '<GlassSwitch checked={enabled} onCheckedChange={setEnabled} ariaLabel="Enable notifications" />',
  },
  {
    id: "slider",
    name: "Slider",
    zh: "滑杆",
    group: "Inputs",
    description: "Direct manipulation, elastic travel and a refracting thumb.",
    summary: "直接拖动、弹性滑行，与真实折射的滑块。",
    api: "GlassSlider",
    props: [
      ["value", "number", "50"],
      ["min / max / step", "number", "0 / 100 / 1"],
      ["onValueChange", "(value: number) => void", "—"],
      ["size", '"default" | "small"', '"default"'],
    ],
    code: '<GlassSlider value={volume} onValueChange={setVolume} ariaLabel="Volume" />',
  },
  {
    id: "tabs",
    name: "Tabs",
    zh: "标签页",
    group: "Navigation",
    description: "Liquid navigation with optional content panels.",
    summary: "液态导航，可选内容面板。",
    api: "GlassTabs",
    props: [
      ["items", "(GlassSegmentItem & { content?: ReactNode })[]", "required"],
      ["value / defaultValue", "string", "first item"],
      ["onValueChange", "(value: string) => void", "—"],
      ["label", "string", '"Sections"'],
    ],
    code: '<GlassTabs items={[{ value: "design", label: "Design" }, { value: "motion", label: "Motion" }, { value: "code", label: "Code" }]} />',
  },
  {
    id: "input",
    name: "Input",
    zh: "输入框",
    group: "Inputs",
    description: "A real native input, framed in the shared glass material.",
    summary: "原生输入体验，配上统一的玻璃材质。",
    api: "GlassInput",
    props: [
      ["label", "string", "—"],
      ["description", "string", "—"],
      ["type", "HTML input type", '"text"'],
      ["value / onChange", "native input props", "—"],
    ],
    code: '<GlassInput label="Your name" placeholder="Ada Lovelace" value={name} onChange={event => setName(event.target.value)} />',
  },
  {
    id: "textarea",
    name: "Textarea",
    zh: "多行输入",
    group: "Inputs",
    description: "Room for a thought, without giving up native editing.",
    summary: "留出书写空间，保留原生编辑和缩放体验。",
    api: "GlassTextarea",
    props: [
      ["label", "string", "—"],
      ["rows", "number", "native default"],
      ["value / onChange", "native textarea props", "—"],
      ["disabled", "boolean", "false"],
    ],
    code: '<GlassTextarea label="Notes" rows={4} placeholder="Something worth keeping…" />',
  },
  {
    id: "checkbox",
    name: "Checkbox",
    zh: "复选框",
    group: "Inputs",
    description: "A small optical surface with native form behavior.",
    summary: "小巧的光学表面，完整的原生表单行为。",
    api: "GlassCheckbox",
    props: [
      ["checked / defaultChecked", "boolean", "false"],
      ["onChange", "ChangeEventHandler", "—"],
      ["name", "string", "—"],
      ["children", "ReactNode", "label"],
    ],
    code: '<GlassCheckbox defaultChecked name="updates">Keep me in the loop</GlassCheckbox>',
  },
  {
    id: "radio-group",
    name: "Radio Group",
    zh: "单选组",
    group: "Inputs",
    description: "One choice. Native keyboard navigation and form values.",
    summary: "一个选择，保留键盘导航与表单值。",
    api: "GlassRadioGroup",
    props: [
      ["label", "string", "required"],
      ["options", "{ value, label, disabled? }[]", "required"],
      ["value / defaultValue", "string", "—"],
      ["onValueChange", "(value: string) => void", "—"],
    ],
    code: '<GlassRadioGroup label="Quality" defaultValue="balanced" options={[{ value: "balanced", label: "Balanced" }, { value: "high", label: "High" }]} />',
  },
  {
    id: "select",
    name: "Select",
    zh: "选择器",
    group: "Inputs",
    description: "A liquid picker fused with its trigger.",
    summary: "与触发器融合的液态选择面板。",
    api: "GlassSelect",
    props: [
      ["label", "string", "—"],
      ["value / onChange", "native select props", "—"],
      ["children", "option elements", "required"],
      ["disabled", "boolean", "false"],
    ],
    code: '<GlassSelect label="Workspace" defaultValue="personal"><option value="personal">Personal</option><option value="team">Team</option></GlassSelect>',
  },
  {
    id: "toggle",
    name: "Toggle",
    zh: "切换按钮",
    group: "Actions",
    description: "A tactile on/off action with a persistent pressed state.",
    summary: "具有持续选中状态的触感按钮。",
    api: "GlassToggle",
    props: [
      ["pressed / defaultPressed", "boolean", "false"],
      ["onPressedChange", "(pressed: boolean) => void", "—"],
      ["children", "ReactNode", "required"],
    ],
    code: "<GlassToggle pressed={saved} onPressedChange={setSaved}>Bookmark</GlassToggle>",
  },
  {
    id: "card",
    name: "Card",
    zh: "卡片",
    group: "Display",
    description: "A quiet container with depth, frost and a directional rim.",
    summary: "带有景深、磨砂与方向性边缘的安静容器。",
    api: "GlassCard",
    props: [
      ["children", "ReactNode", "required"],
      ["className / style", "native HTML props", "—"],
    ],
    code: "<GlassCard><h3>A small workspace</h3><p>Everything in its place.</p></GlassCard>",
  },
  {
    id: "badge",
    name: "Badge",
    zh: "标记",
    group: "Display",
    description: "A compact label, cast from the same material.",
    summary: "由同一材质构成的紧凑标签。",
    api: "GlassBadge",
    props: [
      ["children", "ReactNode", "required"],
      ["className", "string", "—"],
    ],
    code: "<GlassBadge>In progress</GlassBadge>",
  },
  {
    id: "avatar",
    name: "Avatar",
    zh: "头像",
    group: "Display",
    description: "An image or initials with a subtle glass surround.",
    summary: "图片或姓名缩写，置于细腻的玻璃轮廓中。",
    api: "GlassAvatar",
    props: [
      ["name", "string", "required"],
      ["src", "string", "initials fallback"],
      ["size", "number", "48"],
    ],
    code: '<GlassAvatar name="Ada Lovelace" size={56} />',
  },
  {
    id: "progress",
    name: "Progress",
    zh: "进度",
    group: "Feedback",
    description: "A readable, accessible indication of how far you have come.",
    summary: "清晰、可访问的进度反馈。",
    api: "GlassProgress",
    props: [
      ["value", "number", "required"],
      ["max", "number", "100"],
      ["label", "string", '"Progress"'],
    ],
    code: '<GlassProgress value={68} label="Export progress" />',
  },
  {
    id: "alert",
    name: "Alert",
    zh: "提示",
    group: "Feedback",
    description: "Useful context without taking over the screen.",
    summary: "提供必要信息，不打断当前操作。",
    api: "GlassAlert",
    props: [
      ["title", "string", "required"],
      ["role", '"status" | "alert"', '"status"'],
      ["children", "ReactNode", "—"],
    ],
    code: '<GlassAlert title="Changes saved">Your workspace is up to date.</GlassAlert>',
  },
  {
    id: "toast",
    name: "Toast",
    zh: "通知",
    group: "Feedback",
    description: "A small acknowledgement that gracefully makes room again.",
    summary: "及时回应操作，然后轻轻让出空间。",
    api: "GlassToast",
    props: [
      ["open", "boolean", "required"],
      ["title", "string", "required"],
      ["onClose", "() => void", "required"],
      ["duration", "number (ms)", "4000; 0 persists"],
    ],
    code: '<GlassToast open={visible} title="Copied to clipboard" onClose={() => setVisible(false)} />',
  },
  {
    id: "dialog",
    name: "Dialog",
    zh: "对话框",
    group: "Overlays",
    description:
      "A focused task with native focus containment and Escape handling.",
    summary: "聚焦一个任务，支持原生焦点约束与 Escape 退出。",
    api: "GlassDialog",
    props: [
      ["trigger", "ReactElement<button props>", "optional; sets motion origin"],
      ["open", "boolean", "required"],
      ["onOpenChange", "(open: boolean) => void", "required"],
      ["title / description", "string", "title required"],
      ["children", "ReactNode", "—"],
    ],
    code: '<GlassDialog trigger={<GlassButton>Open dialog</GlassButton>} open={open} onOpenChange={setOpen} title="Edit profile"><GlassInput label="Name" /><GlassButton onClick={() => setOpen(false)}>Save</GlassButton></GlassDialog>',
  },
  {
    id: "sheet",
    name: "Sheet",
    zh: "侧边面板",
    group: "Overlays",
    description: "A glass panel that grows from its trigger to the edge.",
    summary: "从触发器生长至屏幕边缘的玻璃面板。",
    api: "GlassSheet",
    props: [
      ["trigger", "ReactElement<button props>", "optional; sets motion origin"],
      ["open", "boolean", "required"],
      ["onOpenChange", "(open: boolean) => void", "required"],
      ["title / description", "string", "title required"],
      ["children", "ReactNode", "—"],
    ],
    code: '<GlassSheet trigger={<GlassButton>Open settings</GlassButton>} open={open} onOpenChange={setOpen} title="Settings"><GlassSwitch ariaLabel="Notifications" /></GlassSheet>',
  },
  {
    id: "popover",
    name: "Popover",
    zh: "浮层",
    group: "Overlays",
    description: "A liquid popup fused with its trigger.",
    summary: "与触发器融合的液态浮层。",
    api: "GlassPopover",
    props: [
      ["open / onOpenChange", "boolean / (open: boolean) => void", "uncontrolled"],
      ["trigger", "ReactNode (button content)", "required"],
      ["label", "string", "required"],
      ["children", "ReactNode", "required"],
    ],
    code: '<GlassPopover trigger="Quick settings" label="Settings"><GlassSlider ariaLabel="Volume" /></GlassPopover>',
  },
  {
    id: "dropdown-menu",
    name: "Dropdown Menu",
    zh: "下拉菜单",
    group: "Overlays",
    description: "A concise action list with arrow-key navigation.",
    summary: "紧凑的操作列表，支持方向键导航。",
    api: "GlassDropdownMenu",
    props: [
      ["trigger", "ReactNode (button content)", "required"],
      ["items", "{ label, disabled?, onSelect }[]", "required"],
      ["label", "string", '"Actions"'],
    ],
    code: '<GlassDropdownMenu trigger="Actions" items={[{ label: "Duplicate", onSelect: duplicate }, { label: "Archive", onSelect: archive }]} />',
  },
  {
    id: "tooltip",
    name: "Tooltip",
    zh: "文字提示",
    group: "Overlays",
    description: "A hint that grows from its trigger.",
    summary: "从触发器延伸的液态提示。",
    api: "GlassTooltip",
    props: [
      ["label", "string", "required"],
      ["children", "ReactElement (focusable)", "required"],
    ],
    code: '<GlassTooltip label="Save this item"><GlassButton>Bookmark</GlassButton></GlassTooltip>',
  },
  {
    id: "accordion",
    name: "Accordion",
    zh: "折叠面板",
    group: "Navigation",
    description: "Expandable content inside one glass surface.",
    summary: "在同一块玻璃内展开与收起内容。",
    api: "GlassAccordion",
    props: [
      ["items", "{ title, content }[]", "required"],
      ["multiple", "boolean", "false"],
      ["lazy", "boolean", "false"],
    ],
    code: '<GlassAccordion items={[{ title: "How does it work?", content: "One shared WebGL2 material." }]} />',
  },
  {
    id: "morph-menu",
    name: "Morph Menu",
    zh: "融变菜单",
    group: "Overlays",
    description: "A trigger that becomes its menu.",
    summary: "触发器融成菜单，关闭后复原。",
    api: "GlassMorphMenu",
    props: [
      ["theme", '"light" | "dark"', "required"],
      ["trigger", "ReactNode", "required"],
      ["menuLabel / openLabel", "string", "required"],
      ["children", "(open: boolean) => ReactNode", "required"],
      ["size", '"small" | "default"', '"small"'],
    ],
    code: `<GlassMorphMenu theme="light" menuLabel="Sort and filter" openLabel="Open menu" trigger={<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="12" r="1.5" fill="currentColor" /><circle cx="12" cy="12" r="1.5" fill="currentColor" /><circle cx="19" cy="12" r="1.5" fill="currentColor" /></svg>}>
        {open => (
          <div className="dg-liquid-menu__scroll">
            <p className="dg-liquid-menu__heading">Sort</p>
            {["Recently played", "Game name"].map(label => <button key={label} className="dg-liquid-menu__sort-row" role="menuitemradio" aria-checked={sort === label} tabIndex={open ? 0 : -1} onClick={() => setSort(label)}><span className="dg-liquid-menu__check">{sort === label && <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="m5 12 4 4L19 6" /></svg>}</span>{label}</button>)}
            <div className="dg-liquid-menu__divider" />
            <p className="dg-liquid-menu__heading">Filter</p>
            <button className="dg-liquid-menu__filter-row" role="menuitemcheckbox" aria-checked={local} tabIndex={open ? 0 : -1} onClick={() => setLocal(!local)}><span />On this device</button>
          </div>
        )}
      </GlassMorphMenu>`,
  },  {
    id: "spotlight",
    name: "Spotlight",
    zh: "折射镜片",
    group: "Media",
    description: "A wandering lens that responds to your pointer.",
    summary: "缓缓游走、响应指针的真实折射镜片。",
    api: "GlassSpotlight",
    props: [
      ["backgroundImage", "string", "grid fallback"],
      ["interactive", "boolean", "true"],
      ["lens", "Partial<LensParams>", "calibrated preset"],
    ],
    code: '<GlassSpotlight backgroundImage="/architecture.jpg" lens={{ lensW: 140, lensH: 140, borderRadius: 140 }} />',
  },
  {
    id: "video",
    name: "Video",
    zh: "视频",
    group: "Media",
    description: "Live video is the substrate for every control.",
    summary: "视频的每一帧，都是玻璃控件的真实底图。",
    api: "GlassVideo",
    props: [
      ["src", "string (same origin or CORS)", "required"],
      ["poster", "string", "—"],
      ["autoPlay / muted / loop", "boolean", "false / true / true"],
      ["labels", "localized labels", "English"],
    ],
    code: '<GlassVideo src="/film.mp4" poster="/poster.webp" />',
  },
] as const;
export const groups = [
  "Actions",
  "Inputs",
  "Navigation",
  "Display",
  "Feedback",
  "Overlays",
  "Media",
];
export const groupZh: Record<string, string> = {
  Actions: "操作",
  Inputs: "输入",
  Navigation: "导航",
  Display: "展示",
  Feedback: "反馈",
  Overlays: "浮层",
  Media: "媒体",
};

const setup: Partial<Record<ComponentId, string>> = {
  button: "const [count, setCount] = useState(0);",
  "button-group": "const [zoom, setZoom] = useState(100);",
  switch: "const [enabled, setEnabled] = useState(false);",
  slider: "const [volume, setVolume] = useState(50);",
  input: 'const [name, setName] = useState("");',
  toggle: "const [saved, setSaved] = useState(false);",
  "morph-menu": 'const [sort, setSort] = useState("Recently played");\n  const [local, setLocal] = useState(false);',
  toast: "const [visible, setVisible] = useState(false);",
  dialog: "const [open, setOpen] = useState(false);",
  sheet: "const [open, setOpen] = useState(false);",
  "dropdown-menu":
    "const [copies, setCopies] = useState(0);\n  const duplicate = () => setCopies(value => value + 1);\n  const archive = () => setCopies(0);",
};
export function exampleCode(id: ComponentId) {
  const entry = catalog.find((item) => item.id === id)!;
  let content: string = entry.code;
  if (id === "toast")
    content =
      "<GlassButton onClick={() => setVisible(true)}>Notify me</GlassButton>\n      " +
      content;
  if (id === "button") content += "\n      <output>{count} clicks</output>";
  if (id === "dropdown-menu")
    content += "\n      <output>{copies} copies</output>";
  const imports = Array.from(
    new Set([
      "GlassStage",
      ...Array.from(content.matchAll(/<([A-Z]\w+)/g), (match) => match[1]),
    ]),
  );
  return `${setup[id] ? 'import { useState } from "react";\n' : ""}import { ${imports.join(", ")} } from "refractive-glass-react/controls";\nimport "refractive-glass-react/controls.css";\n\nexport default function Example() {\n  ${setup[id] ? setup[id] + "\n  " : ""}return (\n    <GlassStage>\n      ${content}\n    </GlassStage>\n  );\n}`;
}

export const componentAliases: Partial<Record<string, ComponentId>> = { "liquid-button": "button", segmented: "tabs", "liquid-menu": "morph-menu" };
