import type { GlassMaterial } from "refractive-glass-react/liquid-glass";
export const materialFields = [
  {
    key: "refractionStrength",
    en: "Refraction",
    zh: "折射强度",
    min: 0,
    max: 0.4,
    step: 0.01,
    initial: 0.11,
  },
  {
    key: "blurStrength",
    en: "Frost",
    zh: "磨砂模糊",
    min: 0,
    max: 4,
    step: 0.1,
    initial: 0.5,
  },
  {
    key: "chromaAmount",
    en: "Dispersion",
    zh: "色散",
    min: 0,
    max: 1.5,
    step: 0.01,
    initial: 0.24,
  },
  {
    key: "magnification",
    en: "Optical depth",
    zh: "光学景深",
    min: 0.5,
    max: 3,
    step: 0.05,
    initial: 1,
  },
  {
    key: "specularStrength",
    en: "Highlight",
    zh: "高光强度",
    min: 0,
    max: 1.5,
    step: 0.01,
    initial: 0.72,
  },
  {
    key: "specularRotation",
    en: "Light angle",
    zh: "高光角度",
    min: 0,
    max: 360,
    step: 1,
    initial: 0,
  },
  {
    key: "glowStrength",
    en: "Glow",
    zh: "辉光",
    min: 0,
    max: 1,
    step: 0.01,
    initial: 0.3,
  },
  {
    key: "edgeStrength",
    en: "Edge definition",
    zh: "边缘轮廓",
    min: 0,
    max: 2,
    step: 0.01,
    initial: 1,
  },
  {
    key: "tintStrength",
    en: "Tint",
    zh: "染色强度",
    min: 0,
    max: 0.6,
    step: 0.005,
    initial: 0.055,
  },
  {
    key: "edgeDepth",
    en: "Edge depth",
    zh: "边缘深度",
    min: 0,
    max: 40,
    step: 0.5,
    initial: 12,
  },
  {
    key: "domeDepth",
    en: "Dome depth",
    zh: "弧面深度",
    min: 0,
    max: 50,
    step: 0.5,
    initial: 18,
  },
  {
    key: "brightness",
    en: "Brightness",
    zh: "亮度",
    min: 0.5,
    max: 2,
    step: 0.01,
    initial: 1,
  },
  {
    key: "glowSpread",
    en: "Glow spread",
    zh: "辉光范围",
    min: 0.1,
    max: 1,
    step: 0.01,
    initial: 0.72,
  },
  {
    key: "glowExponent",
    en: "Glow falloff",
    zh: "辉光衰减",
    min: 0.5,
    max: 8,
    step: 0.1,
    initial: 2,
  },
  {
    key: "edgeWidth",
    en: "Rim width",
    zh: "轮廓宽度",
    min: 0.1,
    max: 3,
    step: 0.05,
    initial: 0.9,
  },
  {
    key: "edgeExponent",
    en: "Rim falloff",
    zh: "轮廓衰减",
    min: 0.5,
    max: 8,
    step: 0.1,
    initial: 2,
  },
  {
    key: "shadowStrength",
    en: "Shadow",
    zh: "阴影强度",
    min: 0,
    max: 0.3,
    step: 0.005,
    initial: 0.11,
  },
  {
    key: "shadowOffset",
    en: "Shadow offset",
    zh: "阴影偏移",
    min: 0,
    max: 30,
    step: 1,
    initial: 18,
  },
  {
    key: "shadowBlur",
    en: "Shadow softness",
    zh: "阴影柔度",
    min: 1,
    max: 40,
    step: 1,
    initial: 26,
  },
  {
    key: "pixelRatio",
    en: "Resolution",
    zh: "渲染分辨率",
    min: 0.5,
    max: 2,
    step: 0.25,
    initial: 2,
  },
  {
    key: "mergeDistance",
    en: "Fusion distance",
    zh: "融合距离",
    min: 0,
    max: 60,
    step: 1,
    initial: 32,
  },
] as const;
export function sanitizeMaterial(value: unknown): GlassMaterial {
  if (!value || typeof value !== "object" || Array.isArray(value)) return {};
  const result: GlassMaterial = {};
  for (const field of materialFields) {
    const number = (value as Record<string, unknown>)[field.key];
    if (typeof number === "number" && Number.isFinite(number))
      result[field.key] = Math.max(field.min, Math.min(field.max, number));
  }
  if (typeof (value as Record<string, unknown>).debug === "boolean")
    result.debug = (value as { debug: boolean }).debug;
  return result;
}
