type Note = readonly [en: string, zh: string];

// Shared meanings by prop name; component-specific entries below take precedence.
const shared: Record<string, Note> = {
  variant: ["Visual weight of the button.", "按钮的视觉强度。"],
  size: ["Control size.", "控件尺寸。"],
  disabled: ["Disables interaction and dims the control.", "禁用交互并降低不透明度。"],
  onClick: ["Called on activation by pointer or keyboard.", "指针或键盘激活时调用。"],
  label: ["Accessible name.", "可访问名称。"],
  orientation: ["Layout axis; arrow keys follow it.", "排列方向，方向键随之切换。"],
  children: ["Content.", "内容。"],
  "…props": ["Passed to the root element.", "透传给根元素。"],
  spacing: ["Distance in CSS pixels at which shapes begin to fuse; 0 keeps them apart.", "形状开始融合的距离（CSS 像素）；0 表示不融合。"],
  checked: ["Controlled on state; omit it for uncontrolled use.", "受控的开启状态；省略则为非受控。"],
  onCheckedChange: ["Called with the next state after a tap, drag or key press.", "点按、拖动或按键后以新状态调用。"],
  ariaLabel: ["Accessible name for the control.", "控件的可访问名称。"],
  value: ["Current value.", "当前值。"],
  "min / max / step": ["Range and increment.", "取值范围与步长。"],
  onValueChange: ["Called when the value changes.", "值变化时调用。"],
  items: ["Entries to render.", "要渲染的条目。"],
  "value / defaultValue": ["Controlled or initial selection.", "受控或初始选中项。"],
  description: ["Supporting text linked to the field.", "与字段关联的说明文字。"],
  type: ["Native input type.", "原生 input 类型。"],
  "value / onChange": ["Native controlled value and change handler.", "原生受控值与变更回调。"],
  rows: ["Visible text lines.", "可见的文本行数。"],
  "checked / defaultChecked": ["Controlled or initial checked state.", "受控或初始勾选状态。"],
  onChange: ["Native change handler.", "原生变更回调。"],
  name: ["Form field name.", "表单字段名称。"],
  options: ["Choices; disabled options are skipped by the keyboard.", "选项；禁用项会被键盘跳过。"],
  "pressed / defaultPressed": ["Controlled or initial pressed state.", "受控或初始按下状态。"],
  onPressedChange: ["Called with the next pressed state.", "以新的按下状态调用。"],
  "className / style": ["Native HTML props on the root.", "根元素上的原生 HTML 属性。"],
  className: ["Extra class on the root.", "根元素的额外类名。"],
  src: ["Media URL.", "媒体地址。"],
  max: ["Upper bound.", "最大值。"],
  title: ["Heading.", "标题。"],
  role: ["status is announced politely; alert interrupts.", "status 礼貌播报；alert 会立即打断。"],
  open: ["Controlled visibility.", "受控的显示状态。"],
  onClose: ["Called on dismissal or when the duration ends.", "关闭或到达时长时调用。"],
  duration: ["Visible time in milliseconds; 0 keeps it until dismissed.", "显示时长（毫秒）；0 表示直到手动关闭。"],
  trigger: ["Content of the trigger button.", "触发按钮的内容。"],
  onOpenChange: ["Called with the next open state.", "以新的打开状态调用。"],
  "title / description": ["Heading and optional description, both announced.", "标题与可选说明，均会被读屏播报。"],
  "open / onOpenChange": ["Optional controlled open state.", "可选的受控打开状态。"],
  multiple: ["Allows several sections open at once.", "允许同时展开多个部分。"],
  lazy: ["Renders section content only after it first opens.", "首次展开后才渲染内容。"],
  theme: ["Color scheme for the specimen's material.", "样本材质的配色方案。"],
  "menuLabel / openLabel": ["Accessible names for the menu and its open state.", "菜单及其打开状态的可访问名称。"],
  backgroundImage: ["Image refracted through the glass.", "透过玻璃折射的图片。"],
  interactive: ["Enables pointer interaction.", "启用指针交互。"],
  lens: ["Lens geometry and optics.", "透镜几何与光学参数。"],
  sources: ["Preferred encodings, tried in order before src.", "优先使用的编码，按顺序在 src 之前尝试。"],
  poster: ["Image shown before the first frame.", "首帧前显示的图片。"],
  "autoPlay / muted / loop": ["Native playback options.", "原生播放选项。"],
  pauseWhenHidden: ["Pauses playback while offscreen or hidden; rendering always pauses.", "离屏或页面隐藏时暂停播放；渲染始终会暂停。"],
  labels: ["Localized control names and messages.", "本地化的控件名称与提示。"],
};

const specific: Record<string, Note> = {
  "button-group:label": ["Accessible name of the group.", "按钮组的可访问名称。"],
  "button-group:children": ["Buttons or links in one glass surface.", "位于同一玻璃表面中的按钮或链接。"],
  "glass-group:children": ["Glass shapes; each direct child becomes one body, up to eight.", "玻璃形状；每个直接子元素成为一个形体，最多八个。"],
  "tabs:items": ["Tabs, with optional panel content.", "标签页，可附带面板内容。"],
  "tabs:label": ["Accessible name of the tab list.", "标签列表的可访问名称。"],
  "input:label": ["Visible label linked to the field.", "与字段关联的可见标签。"],
  "textarea:label": ["Visible label linked to the field.", "与字段关联的可见标签。"],
  "select:label": ["Visible label linked to the field.", "与字段关联的可见标签。"],
  "select:children": ["Native option elements.", "原生 option 元素。"],
  "checkbox:children": ["Label content.", "标签内容。"],
  "radio-group:label": ["Visible group label.", "可见的分组标签。"],
  "toggle:children": ["Button content.", "按钮内容。"],
  "card:children": ["Card content.", "卡片内容。"],
  "badge:children": ["Badge text.", "徽标文字。"],
  "avatar:name": ["Person's name; also the source of the initials.", "人名，也用于生成首字母。"],
  "avatar:src": ["Image URL; initials show when it is missing or fails to load.", "图片地址；缺失或加载失败时显示首字母。"],
  "avatar:size": ["Diameter in CSS pixels.", "直径（CSS 像素）。"],
  "progress:value": ["Completed amount.", "已完成的数量。"],
  "alert:title": ["Heading of the message.", "消息标题。"],
  "alert:children": ["Message body.", "消息正文。"],
  "toast:title": ["Message text.", "消息文字。"],
  "dialog:trigger": ["Optional button the dialog morphs from; without it the focused element is the origin.", "可选的触发按钮，对话框由此变形；省略时以当前聚焦元素为起点。"],
  "sheet:trigger": ["Optional button the sheet morphs from; without it the focused element is the origin.", "可选的触发按钮，面板由此变形；省略时以当前聚焦元素为起点。"],
  "dialog:children": ["Content below the heading.", "标题下方的内容。"],
  "sheet:children": ["Content below the heading.", "标题下方的内容。"],
  "popover:label": ["Accessible name of the panel.", "面板的可访问名称。"],
  "popover:children": ["Panel content.", "面板内容。"],
  "dropdown-menu:items": ["Actions and their select handlers.", "操作项及其选择回调。"],
  "tooltip:label": ["Tooltip text, also the element's accessible description.", "提示文字，同时作为元素的可访问描述。"],
  "tooltip:children": ["The focusable element the tooltip describes.", "提示所描述的可聚焦元素。"],
  "accordion:items": ["Sections with a title and content.", "包含标题与内容的分段。"],
  "morph-menu:trigger": ["Icon inside the round trigger.", "圆形触发按钮中的图标。"],
  "morph-menu:children": ["Menu content, rendered with the current open state.", "菜单内容，按当前打开状态渲染。"],
  "morph-menu:size": ["Menu scale.", "菜单尺寸。"],
  "video:src": ["Fallback source, same origin or CORS-enabled.", "回退视频源，需同源或启用 CORS。"],
};

export const propNote = (id: string, prop: string): Note | undefined => specific[`${id}:${prop}`] ?? shared[prop];
